export const animates = {
  'Attention seekers': [
    'animate__bounce',
    'animate__flash',
    'animate__pulse',
    'animate__rubberBand',
    'animate__shakeX',
    'animate__shakeY',
    'animate__headShake',
    'animate__swing',
    'animate__tada',
    'animate__wobble',
    'animate__jello',
    'animate__heartBeat',
  ],
  'Back entrances': [
    'animate__backInDown',
    'animate__backInLeft',
    'animate__backInRight',
    'animate__backInUp',
  ],
  'Back exits': [
    'animate__backOutDown',
    'animate__backOutLeft',
    'animate__backOutRight',
    'animate__backOutUp',
  ],
  'Bouncing entrances': [
    'animate__bounceIn',
    'animate__bounceInDown',
    'animate__bounceInLeft',
    'animate__bounceInRight',
    'animate__bounceInUp',
  ],
  'Bouncing exits': [
    'animate__bounceOut',
    'animate__bounceOutDown',
    'animate__bounceOutLeft',
    'animate__bounceOutRight',
    'animate__bounceOutUp',
  ],
  'Fading entrances': [
    'animate__fadeIn',
    'animate__fadeInDown',
    'animate__fadeInDownBig',
    'animate__fadeInLeft',
    'animate__fadeInLeftBig',
    'animate__fadeInRight',
    'animate__fadeInRightBig',
    'animate__fadeInUp',
    'animate__fadeInUpBig',
    'animate__fadeInTopLeft',
    'animate__fadeInTopRight',
    'animate__fadeInBottomLeft',
    'animate__fadeInBottomRight',
  ],
  'Fading exits': [
    'animate__fadeOut',
    'animate__fadeOutDown',
    'animate__fadeOutDownBig',
    'animate__fadeOutLeft',
    'animate__fadeOutLeftBig',
    'animate__fadeOutRight',
    'animate__fadeOutRightBig',
    'animate__fadeOutUp',
    'animate__fadeOutUpBig',
    'animate__fadeOutTopLeft',
    'animate__fadeOutTopRight',
    'animate__fadeOutBottomRight',
    'animate__fadeOutBottomLeft',
  ],
  Flippers: [
    'animate__flip',
    'animate__flipInX',
    'animate__flipInY',
    'animate__flipOutX',
    'animate__flipOutY',
  ],
  Lightspeed: [
    'animate__lightSpeedInRight',
    'animate__lightSpeedInLeft',
    'animate__lightSpeedOutRight',
    'animate__lightSpeedOutLeft',
  ],
  'Rotating entrances': [
    'animate__rotateIn',
    'animate__rotateInDownLeft',
    'animate__rotateInDownRight',
    'animate__rotateInUpLeft',
    'animate__rotateInUpRight',
  ],
  'Rotating exits': [
    'animate__rotateOut',
    'animate__rotateOutDownLeft',
    'animate__rotateOutDownRight',
    'animate__rotateOutUpLeft',
    'animate__rotateOutUpRight',
  ],
  Specials: ['animate__hinge', 'animate__jackInTheBox', 'animate__rollIn', 'animate__rollOut'],
  'Zooming entrances': [
    'animate__zoomIn',
    'animate__zoomInDown',
    'animate__zoomInLeft',
    'animate__zoomInRight',
    'animate__zoomInUp',
  ],
  'Zooming exits': [
    'animate__zoomOut',
    'animate__zoomOutDown',
    'animate__zoomOutLeft',
    'animate__zoomOutRight',
    'animate__zoomOutUp',
  ],
  'Slanimateiding entrances': [
    'animate__slideInDown',
    'animate__slideInLeft',
    'animate__slideInRight',
    'animate__slideInUp',
  ],
  'Slanimateiding exits': [
    'animate__slideOutDown',
    'animate__slideOutLeft',
    'animate__slideOutRight',
    'animate__slideOutUp',
  ],
};

export const animTranslations: Record<string, string> = {
  '': '无',
  animate__bounce: '弹跳',
  animate__flash: '闪烁',
  animate__pulse: '脉冲',
  animate__rubberBand: '橡皮筋',
  animate__shakeX: '左右摇晃',
  animate__shakeY: '上下摇晃',
  animate__headShake: '摇头',
  animate__swing: '秋千',
  animate__tada: '噔噔',
  animate__wobble: '摇摆',
  animate__jello: '果冻',
  animate__heartBeat: '心跳',
  animate__backInDown: '从上回入',
  animate__backInLeft: '从左回入',
  animate__backInRight: '从右回入',
  animate__backInUp: '从下回入',
  animate__bounceIn: '弹入',
  animate__bounceInDown: '从上弹入',
  animate__bounceInLeft: '从左弹入',
  animate__bounceInRight: '从右弹入',
  animate__bounceInUp: '从下弹入',
  animate__fadeIn: '渐显',
  animate__fadeInDown: '从上滑入',
  animate__fadeInDownBig: '从上长滑入',
  animate__fadeInLeft: '左滑入场',
  animate__fadeInLeftBig: '左长滑入',
  animate__fadeInRight: '右滑入场',
  animate__fadeInRightBig: '右长滑入',
  animate__fadeInUp: '从下滑入',
  animate__fadeInUpBig: '从下长滑入',
  animate__fadeInTopLeft: '左上滑入',
  animate__fadeInTopRight: '右上滑入',
  animate__fadeInBottomLeft: '左下滑入',
  animate__fadeInBottomRight: '右下滑入',
  animate__flip: '翻转',
  animate__flipInX: 'X轴翻入',
  animate__flipInY: 'Y轴翻入',
  animate__lightSpeedInRight: '光速右入',
  animate__lightSpeedInLeft: '光速左入',
  animate__rotateIn: '旋转进入',
  animate__rotateInDownLeft: '左上旋入',
  animate__rotateInDownRight: '右上旋入',
  animate__rotateInUpLeft: '左下旋入',
  animate__rotateInUpRight: '右下旋入',
  animate__jackInTheBox: '弹出盒子',
  animate__rollIn: '滚入',
  animate__zoomIn: '放大渐显',
  animate__zoomInDown: '向下放大',
  animate__zoomInLeft: '向左放大',
  animate__zoomInRight: '向右放大',
  animate__zoomInUp: '向上放大',
  animate__slideInDown: '顶部滑入',
  animate__slideInLeft: '左侧滑入',
  animate__slideInRight: '右侧滑入',
  animate__slideInUp: '底部滑入',
};

export const categoryTranslations: Record<string, string> = {
  'Attention seekers': '强调特效',
  'Back entrances': '回退进入',
  'Bouncing entrances': '弹跳进入',
  'Fading entrances': '渐变进入',
  Flippers: '翻转特效',
  Lightspeed: '光速进入',
  'Rotating entrances': '旋转进入',
  Specials: '特殊特效',
  'Zooming entrances': '缩放进入',
  'Slanimateiding entrances': '滑动进入',
};
